version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: cs2102-project
      POSTGRES_PASSWORD: cs2102-project
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
